### ISSUE TITLE
Simple save/restore pattern

### ISSUE THREAD

**Issue by shadowspawn** [ljharb/mock-property#2]
For simple use by people unfamiliar with descriptors, but wanting to safely put back the old state after overwriting a property, a simple save and restore might be useful. Two cases where I have wanted to do this are setting an environment variable for a unit test, and hacking `process.argv` to run a unit test. 

I suspect this is equivalent to is a delete in the first operation to clear the way for whatever I do, and perhaps doesn't make sense as a "mock" pattern. Could be wishful thinking that this might be a possible helper routine. 😄 

Edit: a better description of the usage pattern might be "stash" and "restore".

e.g.
```js
var restoreArgv = mockProperty(process, 'argv');
process.argv = ['someApp', 'someFile', 'arg1'];
// run test
restoreArgv();
```

**Comment by ljharb** [comment]
You can do this with a `{ delete: true }` options bag as the third argument, otherwise it should work the same.

In the general, case, that wouldn’t be enough because there still might be a setter in an inheritance chain, but in this case that should be fine. The general solution would be to pass the new array as “value” in the options bag.
